# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 张然的博客 # ex. I m Chuan
name: ZhangRyze # ex. DONGChuan
email: zhangryze@gmail.com
tel: 15620920109
location: 天津 # ex. Nice, France
company: 爱普海德（天津）科技有限公司
company_url: www.armyhorse.com
github_url: https://github.com/BurningYoung # ex. https://github.com/DONGChuan
description: description_of_your_web_site
favicon: blog_icon.jpg # Image must be in assets/images
repository: BurningYoung/BurningYoung.github.io/ # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://BurningYoung.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
# skill List
skill_list: [
    '熟练掌握 HTML、CSS、javascript，掌握HTML5、CSS3，熟悉Less',
    '熟练掌握 jQuery库，用过swiper、bigcolorpicker、dropzone等jQuery插件',
    '熟练掌握 Bootstrap、JqueryUI，了解MUI等UI框架',
    '熟练掌握 Vue.js，了解Vue-router、vue-devtools、vue-cli等插件和工具',
    '熟练掌握 localstorage、sessionStorage、Cookie等本地储存',
    '熟练掌握 HTTP协议、AJAX技术，了解跨域技术',
    '熟练使用 HBuilder、WebStorm、Sublime Text等IDE工具，了解eclipse',
    '熟练使用 photoshop、illustrator、Axure RP等设计软件; 熟悉SVN、Git',
    '了解Hybrid App、WebApp开发，有Hybrid App、WebApp开发经验',
    '了解NodeJS，有基于NodeJS开发的经验',
    '熟悉Tomcat，有过Apache Tomcat调优尝试',
    '有阿里云ECS、微信应用开发和开放平台使用经验，有自己的微信公众账号'
]
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
